image: mieubrisse/test-gitpod

tasks:
  - name: Kurtosis
    command: |
      # Load the images we cached
      tar -xOzf /docker-images/engine.tgz | docker load
      tar -xOzf /docker-images/core.tgz | docker load

      # Notify of a Gitpod usage
      kurtosis run github.com/fake-package/fake-package-purely-for-analytics &> /dev/null
      kurtosis clean -a 

      code README.md
      clear  

      # If a Kurtosis package was specified as an envvar, run it
      [ -n "${KURTOSIS_PACKAGE_LOCATOR}" ] && kurtosis run "${KURTOSIS_PACKAGE_LOCATOR}"

ports:
  - name: Kurtosis Engine GRPC Port
    description: The Kurtosis engine's GRPC listen port
    port: 9710
    onOpen: ignore

vscode:
  extensions:
    - Kurtosis.kurtosis-extension
